'use strict';

const express = require('express');
const asyncHandler = require('../utils/asyncHandler');
const authRoutesweb = require('./auth.routes.js');
const userRoutes = require('./user.routes.js');
const departRoutes = require('./department.routes.js');
const designationRoutes = require('./designation.routes.js');
const { health } = require('../controllers/health.controller.js');
const roleRoutes = require('./roles.routes.js');
const qualificationRoutes = require('./qualification.routes.js');
const skillsRoutes = require('./skills.routes.js');
const holidayRoutes = require('./holiday.routes.js');
const employeeRoutesweb = require('./employee.routes.js');
const clientRoutesweb = require('./client.routes.js');
const leaveTypeRoutesWeb = require('./leaveType.routes.js');
const leaveRoutes = require('./leave.routes.js');
const employeeLeaveRoutesWeb = require('./empLeave.routes.js');
const branchRoutesweb = require('./branch.routes.js');
const attendenceRoutes = require('./attendence.routes.js');
const dailyWorkSheetRoutes = require('./dailyWorksheet.routes.js');
const ReportRoutes = require('./report.routes.js');
const ShiftRoutes = require('./shift.routes.js');
const RolePermissionRoutes = require('./rolePermission.routes.js');
const ProjectRoutes = require('./project.routes.js');
const TaskRoutes = require('./task.routes.js');
const salaryheadRoutes = require('./salaryHead.routes.js');
const payrollRoutes = require('./payroll.routes.js');
const payrollStructureRoutes = require('./payrollStructure.routes.js');
const allowanceRoutes = require('./allowancetransaction.routes.js');
const roomsRoutes = require('./room.route.js');
const rentRoutes = require('./rent.route.js');

const router = express.Router();

router.get('/health', asyncHandler(health));
router.use('/auth', authRoutesweb);
router.use('/user', userRoutes);
router.use('/department', departRoutes);
router.use('/designation', designationRoutes);
router.use('/roles', roleRoutes);
router.use('/qualification', qualificationRoutes);
router.use('/skills', skillsRoutes);
router.use('/shift', ShiftRoutes);
router.use('/holiday', holidayRoutes);
router.use('/client', clientRoutesweb);
router.use('/employee', employeeRoutesweb);
router.use('/leavetype', leaveTypeRoutesWeb);
router.use('/leave', leaveRoutes);
router.use('/employeeLeave', employeeLeaveRoutesWeb);
router.use('/branch', branchRoutesweb);
router.use('/attendance', attendenceRoutes);
router.use('/worksheet', dailyWorkSheetRoutes);
router.use('/attendance', ReportRoutes);
router.use('/rolePerm', RolePermissionRoutes);
router.use('/project', ProjectRoutes);
router.use('/task', TaskRoutes);
router.use('/salaryhead', salaryheadRoutes);
router.use('/payroll', payrollRoutes);
router.use('/payrollStructure', payrollStructureRoutes);
router.use('/allowance', allowanceRoutes);
router.use('/room', roomsRoutes);
router.use('/rent', rentRoutes);



// for app 
const authRoutes = require('./authRoutes');
const attendanceRoutes = require('./attendanceRoutes');
const markAttendanceRoutes = require('./markattendance');
const reportRoutes = require('./reportRoutes');
const taskRoutes = require('./taskRoutes');
const getTaskRoutes = require('./getTaskRoutes');
const branchRoutes = require('./branchRoutes');
const clientRoutes = require('./clientRoutes');
const employeeRoutes = require('./employeeRoutes');
const leaveTypeRoutes = require('./leaveTypeRoutes');
const employeeLeaveRoutes = require('./employeeLeaveRoutes');
const applyLeaveRoutes = require('./applyleaveRoutes');
const payslipRoutes = require('./payslipRoutes');
const rolePermissionRoutes = require('./rolePermissionRoutes');
const monthReportRoutes = require('./monthReportRoutes');
const attendanceTodayRoutes = require('./attendanceTodayRoutes');
const taskReportRoutes = require('./taskReportRoutes');
const departmentRoutes = require('./departmentRoutes');
const allempleaveRoutes = require('./allempleaveRoutes');
const logoutRoutes = require('./logoutRoutes');
const forgetPasswordRoutes = require('./forgetPasswordRoutes');
const generateOtpRoutes = require('./generateOtpRoutes');
const verifyOtpRoutes = require('./verifyOtpRoutes');
const sendOtpRoutes = require('./sendOtpRoutes');
router.use('/auth/app', authRoutes);
router.use('/', attendanceRoutes);
router.use('/', markAttendanceRoutes);
router.use('/report', reportRoutes);
router.use('/', taskRoutes);
router.use('/', getTaskRoutes);
router.use('/', branchRoutes);
router.use('/', clientRoutes);
router.use('/', employeeRoutes);
router.use('/', leaveTypeRoutes);
router.use('/', employeeLeaveRoutes);
router.use('/', applyLeaveRoutes);
router.use('/', payslipRoutes);
router.use('/', rolePermissionRoutes);
router.use('/', monthReportRoutes);
router.use('/', attendanceTodayRoutes);
router.use('/', taskReportRoutes);
router.use('/', departmentRoutes);
router.use('/', allempleaveRoutes);
router.use('/', logoutRoutes);
router.use('/', forgetPasswordRoutes);
router.use('/', generateOtpRoutes);
router.use('/', verifyOtpRoutes);
router.use('/', sendOtpRoutes);

module.exports = router;
